// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCopdW0wIofxuCosxu-_I6cxvAqepMS3W0',
    appId: '1:677839630280:android:eb117f795c660eaa791afd',
    messagingSenderId: '677839630280',
    projectId: 'animeverse-431f6',
    storageBucket: 'animeverse-431f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsu-YRi_WF6du-AksyHsxH5lxiW29GvxE',
    appId: '1:677839630280:ios:20e83ad64bd64b12791afd',
    messagingSenderId: '677839630280',
    projectId: 'animeverse-431f6',
    storageBucket: 'animeverse-431f6.firebasestorage.app',
    androidClientId: '677839630280-7s5bstlevukiliqc1tmigs06n71q0c42.apps.googleusercontent.com',
    iosClientId: '677839630280-25mdnbt9ub4hko7162ri4o03ig99k365.apps.googleusercontent.com',
    iosBundleId: 'com.example.animeverse',
  );
}
